# Azure DevOps pipeline for the project
trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m -Dusername=PAT -Dpassword=$(System.AccessToken)'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean package release:prepare release:perform -P release'
      options: '-B -DscmCommentPrefix="[skip ci]"'